---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-helm-tls-ca-config
  namespace: flux
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIE6jCCAtKgAwIBAgIUHsJVSYbAuy3sJRUfznmDmb5a6xcwDQYJKoZIhvcNAQEN
    BQAwDTELMAkGA1UEAxMCQ0EwHhcNMTkxMDExMDQ0MTAwWhcNMjQxMDA5MDQ0MTAw
    WjANMQswCQYDVQQDEwJDQTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
    AL5LYXTi/0kdKbqqLIW2FjUhWyABfUqjmYf/vVEJLt3jbKLnipY9BSAge4hUmVy2
    39em6AUvp1H7cAAc75KFJhAYA93J4t1w4Du1JOk8XuHkIxWZ9xPqkt3IN9seqg3L
    8Hu9/723+brGBWswxMh1XPn74actEbqcmj5XubgJmJ62SMpL0gwUqvU3GvtPpHph
    Nn3Xwagx93t5opM2p9oSRcrpJtXhZ0BB2DQRio1vl7KteQAfPhujfFpaf0aWT13a
    Jz4sPagtlZUvZKwOOiYlOrvReCq5KcvXP7pid1LSjOA8gS50RkOIdTA9mUpAl0XM
    hyYh1VQyM4aB6jG5fVrtTBaO/EvMIQPnU3j9t/TNI/RrixbXm1RgjhPsSmzdaHjy
    Txf9q57YsZC6L6gykm+BME1+oETfmUWpp7ulI61Bj/2Kebxk5JKYirJVJqeSj5Ok
    OKblmJm1hJGpGucx71dtWowGIVkKTZtyEFY7vqB0KpHZ0u+fHQfjICRtH3l773so
    AyKi/eWDJREp3SZF8JNzZP2ipuElP1qGZUJZLRfWRC7r+esPQ6qk/HjCVq3EBVyL
    WIVfHow9Zq77Wvp5nlREs3jaX4SySkbw2bdFSywQ4Wd1gPu2ugVOv9Fas7bwmx8h
    tI6Qn/tHeF0tMMqwk88/78jgg4KAfXs/8IqouS8pj6drAgMBAAGjQjBAMA4GA1Ud
    DwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTyskU4yk19hR3x
    +CbZ5FAAWnJ5MjANBgkqhkiG9w0BAQ0FAAOCAgEAtgE4w05mGXskv8dhTx1kyOIP
    PO3zMj122wVYqwwXPmynuw9APCwDg1TxAUPreZhu74Y6UU3UkP3gB59tt1WjRFrY
    iQVHOnk40uJ29pIZ5rczEodyOK1ifr4q6ivZPxMg3mTg78N62R5TCFPb2t3QyDRN
    J90cNSgpShw35LL5b8BMgLrlqgj88xWYA9uv5j0LZ6iraupEB4FkBQz/CLXORrdg
    QjQMy+CYVF2A/uNUb8jiQGxOnMCD4D5ZEFoJeoEM/GAHGkHeirqyjODJlOoXPVYa
    qi8g4ERXdk14PH/FolZENVNk+a/G930pMp5iDHBxqi3ULXOlWR4a2PK6lDAUci2h
    wP0u7VMsM7V1mbgiHea9S0b7opgjKjDip5EaMBR8sNkCp/QXjxKj7iQR8dEdZMa/
    UGMeLFBnTp6kAloIpcpG6eUNtxXdCqhFAKoEd/ws9rTRYkPkLUOoQpiEaWTCBULk
    +g5uhWFgjMVGFnntBdc6cyQwgN2mjDokbgYGbjNmrshY3WulA4EN6mQ2tfMzjZWX
    PMICuSN3XeDwbGMQhDOBA9R1XSqvqbVtztLkrJ1/OzOfduryIXoq0tkIxfSCrfCB
    2+ghRebjqr+K3jSy3a7VtYCWnrpFydPV/Y9SmQPyirbxL4+1kpSOaqNiOkrEd5o+
    7wUwZlzEdKjA9B/uTnY=
    -----END CERTIFICATE-----
    
